# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A Journal
author: Dylan Hurd
author_link: https://twitter.com/dr_hurd
author_description: >
  I like to write, and sometimes I like the results enough to post them here.
email: me@dylanhurd.com
description: > # this means to ignore newlines until "baseurl:"
  A personal blog that is little more than sound and fury.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dylanhurd.com" # the base hostname & protocol for your site

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
#typekit_kit_id: zsw1vdp

# Build settings
gems: []
markdown: kramdown
permalink: pretty

